# POST http://localhost:3003/api/blogs
# Content-Type: application/json

# {
#     "title": "Oprah",
# 	"author": "Oprah Winfrey",
# 	"url": "http://www.google.com",
# 	"likes": 1341341
# }

# GET http://localhost:3003/api/blogs

GET http://localhost:3003/api/users

# POST http://localhost:3003/api/users
# Content-Type: application/json

# {
#     "name": "Tlkasjfalsdjf",
#     "username": "tiasdlfjasldjf",
#     "password": "l"
# }